openapi: 3.0.3
info:
  title: Галерея
  version: 1.0.11
  description: Авторизация 
paths:
  /auth:
    post:
      requestBody:
        description: Авторизует пользователя
        content:
          application/json:
            schema:
              $ref: '#/common/models/components/schemas/Auth'
        required: true
      responses:
        '200':
          description: Авторизация прошла успешно
          content:
            application/json:
              schema:
                $ref: '#/common/models/components/schemas/User'          
        '400':
          description: Неправильно введен логин или пароль
  /logout:
    post:
      responses:
        '200':
          description: Логаут выполнен успешно
        '403':
          description: Что-то пошло не так. Попробуйте снова
        '401':
          description: Пользователь не авторизован
  /refresh_token:
    post:
      requestBody:
        description: Обновляет пару токенов
        content:
          application/json:
            schema:
              $ref: '#/common/models/components/schemas/Tokens'
      responses:
        '200':
          description: Обновление пары токенов прошло успешно
          content:
            application/json:
              schema:
                $ref: '#/common/models/components/schemas/Tokens'
        '403':
          description: Что-то пошло не так. Попробуйте позже